workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build


orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    working_directory: ~/shareYourTravels
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run:
          name: hello
          command: echo hello
  deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - run:
          name: world
          command: echo world
 